// Generated by scripts/check-equipment-profiles.py; change profile revision when semantics change.
#pragma once
namespace kerumo {
constexpr char Su600ProfileHash[]="341d1d5215ff61342ebb09662215912bbe133afe4541d952c7308bb29b1dab4e";
}
