import { spawnSync } from "node:child_process";

// Extend this gate as older modules are touched; avoid unrelated formatting churn.
const files = [
  "src/features/device-events.tsx",
  "src/components/refresh-settings.tsx",
  "src/features/refresh-actions.tsx",
  "src/components/telemetry-chart.tsx",
  "src/features/telemetry-preferences.ts",
  "src/lib/api/telemetry-series.ts",
  "src/proxy.ts",
  "src/features/operations/shared.tsx",
  "src/features/operations/console.tsx",
  "src/features/operations/people.tsx",
  "src/features/operations/organizations.tsx",
  "src/features/operations/observability.tsx",
  "src/app/operations/page.tsx",
  "src/app/staff.css",
  "src/app/customer.css",
  "src/app/layout.tsx",
  "src/app/not-found.tsx",
  "src/components/controller-qr.tsx",
  "src/components/controller-qr-code.tsx",
  "src/components/text-field.tsx",
  "src/components/ui.tsx",
  "src/components/use-input-validation.ts",
  "src/features/login.tsx",
  "src/features/login-cooldown.ts",
  "src/features/schedule-panel.tsx",
  "src/features/login-model.ts",
  "src/features/controller-lifecycle.tsx",
  "src/features/equipment-actions.tsx",
  "src/features/factory-controller-actions.tsx",
  "src/features/equipment-passport.tsx",
  "src/features/account-gate.tsx",
  "src/features/account-security.tsx",
  "src/features/auth-session.tsx",
  "src/features/auth-session-runtime.ts",
  "src/features/connect.tsx",
  "src/features/device-overview.tsx",
  "src/features/command-controls.tsx",
  "src/features/command-journal.tsx",
  "src/features/telemetry-history.tsx",
  "src/features/inventory.tsx",
  "src/features/alarms.tsx",
  "src/features/notifications.tsx",
  "src/lib/device-labels.ts",
  "src/features/factory.tsx",
  "src/features/recover.tsx",
  "src/features/controller-activation.tsx",
  "src/features/create-personal-account.tsx",
  "src/features/email-link.ts",
  "src/features/registration.tsx",
  "src/features/invitation.tsx",
  "src/features/organization-members.tsx",
  "src/features/use-account-action.ts",
  "src/features/use-elapsed-seconds.ts",
  "src/lib/api/onboarding.ts",
];
const result = spawnSync(process.execPath, ["node_modules/prettier/bin/prettier.cjs", "--check", ...files], {
  stdio: "inherit",
});
if (result.error) throw result.error;
process.exit(result.status ?? 1);
