"""Keep the firmware's accepted immutable profile hash in sync with the catalog."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    profiles = json.loads((ROOT / "backend/app/data/equipment_profiles.json").read_text(encoding="utf-8"))
    profile = next(item for item in profiles if item["id"] == "suswe.su600.modbus" and item["version"] == 1)
    digest = hashlib.sha256(json.dumps(profile, ensure_ascii=True, sort_keys=True, separators=(",", ":"), allow_nan=False).encode("ascii")).hexdigest()
    content = '// Generated by scripts/check-equipment-profiles.py; change profile revision when semantics change.\n#pragma once\nnamespace kerumo {\nconstexpr char Su600ProfileHash[]="' + digest + '";\n}\n'
    path = ROOT / "firmware/kerumo_v3/src/profile_revision.h"
    if args.write:
        path.write_text(content, encoding="ascii")
    elif not path.exists() or path.read_text(encoding="ascii") != content:
        raise SystemExit("Equipment profile hash differs; review the revision and run --write")
    print("PASS: equipment profile catalog / firmware hash")


if __name__ == "__main__":
    main()
